In [1]:
# run this by itself to run r 
%load_ext rpy2.ipython

Error importing in API mode: ImportError('On Windows, cffi mode "ANY" is only "ABI".')
Trying to import in ABI mode.

In [2]:
import pandas as pd
df = pd.read_csv("C:/Users/tyler/OneDrive/Documents/GitHub/work_to_show/Kaggle/spotify_global_trends.csv")
df.head()

,track_name,artist_name,streams,stream_change,7day,genre,country,pos,days,viral_score,trend,popularity_category,longevity
0,SWIM,BTS,11273830,-3370522,25918182,K-Pop,KR,1,2,37192012,Falling,Trending,New
1,Body to Body,BTS,6815694,-4369341,18000729,K-Pop,KR,2,2,24816423,Falling,Trending,New
2,Babydoll,Dominic Fike,5733862,178968,36599831,Alternative Pop,Florida,3,119,42333693,Rising,Trending,Evergreen
3,Hooligan,BTS,5338608,-3396855,14074071,K-Pop,KR,4,2,19412679,Falling,Trending,New
4,FYA,BTS,5196767,-2873904,13267438,K-Pop,KR,5,2,18464205,Falling,Trending,New

In [5]:
%%R -i df
colnames(df) # col names 
unique(df$genre) # unique items in the genre

 [1] "K-Pop"                  "Alternative Pop"        "Uk Garage"
 [4] "Pop"                    "Synth-Pop"              "Offizielle Charts"
 [7] "Rap"                    "Indie Pop"              "Reggaeton"
[10] "Rock"                   "Billboard Hot 100"      "Alternative Rock"
[13] "New Wave"               "Psychedelic Rock"       "Country"
[16] "Dancehall"              "Electronic"             "Hip Hop"
[19] "Regional Mexicano"      "Dance-Pop"              "Girl Group"
[22] "Indie Rock"             "Contemporary R&B"       "R&B"
[25] "Nu Metal"               "Falcom"                 "Pop Soul"
[28] "Folk Pop"               "Swamp Rock"             "Special Purpose Artist"
[31] "Grunge"                 "Latin"                  "Hard Rock"
[34] "Dance"                  "Toronto"                "Soundtrack"
[37] "Britpop"                "Dolby Atmos"            "Soul"

In [10]:
# genre streamed the most
genre_streamed = (
    df
    .groupby('genre')                         # pandas uses groupby, not group_by
    .agg(streams=('streams', 'sum'))          # sum streams per genre
    .sort_values('streams', ascending=False)  # sort descending
    .reset_index()                            # bring genre back as a column
)
genre_streamed

                     genre   streams
0                      Pop  96866003
1                    K-Pop  72752485
2                     Rock  24820619
3                Reggaeton  17181163
4        Billboard Hot 100  12961759
5                Indie Pop  12901895
6        Regional Mexicano  12704416
7         Alternative Rock  11782572
8                  Hip Hop  11718989
9          Alternative Pop   9993132
10       Offizielle Charts   8530964
11                     R&B   7540492
12              Electronic   7079567
13                     Rap   5135217
14                New Wave   4977399
15               Dance-Pop   4808187
16              Indie Rock   4781294
17               Uk Garage   4738329
18               Synth-Pop   4108838
19        Psychedelic Rock   3926122
20                Nu Metal   2998438
21                Folk Pop   2956839
22                  Grunge   2678263
23                 Country   2169091
24               Dancehall   2154338
25              Girl Group   1850006
26        Contemporary R&B   1807214
27                  Falcom   1639753
28                Pop Soul   1558344
29              Swamp Rock   1507387
30  Special Purpose Artist   1466813
31                   Latin   1380148
32               Hard Rock   1367839
33                   Dance   1364636
34                 Toronto   1349819
35              Soundtrack   1326162
36                 Britpop   1286520
37             Dolby Atmos   1245007
38                    Soul   1203160